/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"
#include "g_canvas.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *knob_class;
t_widgetbehavior knob_widgetbehavior; // This represents the external GUI

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _knob {
   t_object x_obj;
   t_outlet * x_outlet_value_float;
   t_inlet * x_inlet_value_float;
   t_float min;
   t_float max;
   t_float value;
   t_glist *glist;
   t_canvas *canvas;
   t_int size;
   t_int last_x;
   t_int last_y;
} t_knob;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * knob_new(t_floatarg, t_floatarg, t_floatarg, t_floatarg);// Constructor
void knob_destroy(t_knob *x); //Destructor
void knob_size(t_knob *x, t_floatarg f0); // Message function
void knob_min(t_knob *x, t_floatarg f0); // Message function
void knob_max(t_knob *x, t_floatarg f0); // Message function
void knob_value_float_method(t_knob *x, t_floatarg f);// Active inlet function
void knob_bang_bang_method(t_knob *x);// Active inlet function
//GUI stuff
static void knob_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2);
static void knob_vis(t_gobj *z, t_glist *glist, int vis);
static void knob_displace(t_gobj *z, t_glist *glist,int dx, int dy);
static void knob_select(t_gobj *z, t_glist *glist, int state);
static void knob_delete(t_gobj *z, t_glist *glist);
static void knob_save(t_gobj *c, t_binbuf *b);
static void knob_set_properties(t_knob *x, t_floatarg size,
                t_floatarg min, t_floatarg max, t_floatarg value);
static void knob_properties(t_gobj *c, t_glist *list);
static void knob_draw(t_knob *x);
static void knob_erase(t_knob *x);
static void knob_refresh(t_knob *x);
// ---------------------------------------------------
// knob_value
// ---------------------------------------------------
void knob_value_float_method(t_knob  *x, t_floatarg f){
    x->value = f;
    knob_bang_bang_method(x);
}

// ---------------------------------------------------
// knob_bang
// ---------------------------------------------------
void knob_bang_bang_method(t_knob *x){
    if(x->value > x->max)
        x->value = x->max;
    if(x->value < x->min)
        x->value = x->min;
    outlet_float(x->x_outlet_value_float, x->value);
    knob_refresh(x);
}

// ---------------------------------------------------
// knob_size
// ---------------------------------------------------
void knob_size(t_knob *x, t_floatarg f0){
    x->size = (t_int)f0;
    knob_erase(x);
    knob_draw(x);
}

// ---------------------------------------------------
// knob_min
// ---------------------------------------------------
void knob_min(t_knob *x, t_floatarg f0){
    x->min = f0;
    knob_erase(x);
    knob_draw(x);
}


// ---------------------------------------------------
// knob_max
// ---------------------------------------------------
void knob_max(t_knob *x, t_floatarg f0){
    x->max = f0;
    knob_erase(x);
    knob_draw(x);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * knob_new(t_floatarg size,
                t_floatarg min, t_floatarg max, t_floatarg value){
   t_knob *x = (t_knob *) pd_new(knob_class);
   x->x_inlet_value_float = floatinlet_new(&x->x_obj, &x->value);
   x->x_outlet_value_float = outlet_new(&x->x_obj, gensym("float"));
   knob_set_properties(x, size, min, max, value);
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void knob_destroy(t_knob *x) {
   inlet_free(x->x_inlet_value_float);
   outlet_free(x->x_outlet_value_float);
   gfxstub_deleteforkey(x);
}

//GUI stuff ---------------------------------------

// ---------------------------------------------------
// Mouse press
// ---------------------------------------------------
static void knob_mousepress(t_knob* x, t_float xpix, t_float ypix){
    // If edit mode, give up!
    if (x->glist->gl_edit)
        return;
    x->last_x = xpix - x->x_obj.te_xpix;
    x->last_y = ypix - x->x_obj.te_ypix;
}

// ---------------------------------------------------
// Mouse Drag event
// ---------------------------------------------------
static void knob_mousemotion(t_knob* x, t_float xpix, t_float ypix){
    // If edit mode, give up!
    if (x->glist->gl_edit)
        return;
    t_int posx = xpix - x->x_obj.te_xpix;
    t_int posy = ypix - x->x_obj.te_ypix;

    if(posx > x->last_x)
        x->value += (x->max - x->min) * 0.01;
    if(posx < x->last_x)
        x->value -= (x->max - x->min) * 0.01;
    x->last_x = posx;

    // y axis is inverted
    if(posy < x->last_y)
        x->value += (x->max - x->min) * 0.01;
    if(posy > x->last_y)
        x->value -= (x->max - x->min) * 0.01;
    x->last_y = posy;

    knob_bang_bang_method(x);
}

// ---------------------------------------------------
// Refresh
// ---------------------------------------------------
static void knob_refresh(t_knob *x){
   int arc = -(x->value * 270) / (x->max - x->min);
   sys_vgui(".x%lx.c itemconfigure %xneed -start %d\n", x->canvas, x, arc - 135);
   sys_vgui(".x%lx.c itemconfigure %xarc -extent %d\n", x->canvas, x, arc);

}

// ---------------------------------------------------
// Draw
// ---------------------------------------------------
static void knob_draw(t_knob *x){
    int x0 = x->x_obj.te_xpix;
    int y0 = x->x_obj.te_ypix;

   // INLET ESQUERDO
   sys_vgui(".x%lx.c create rectangle %d %d %d %d -tags {%xrr} -fill #FFFFFF\n",
      x->canvas,
      x0 + 0,
      y0 + 0,
      x0 + 8,
      y0 + 2,
      x
      );

   // INLET ESQUERDO
   sys_vgui(".x%lx.c create rectangle %d %d %d %d -tags {%xrr} -fill #FFFFFF\n",
      x->canvas,
      x0 + x->size - 8,
      y0 + 0,
      x0 + x->size,
      y0 + 2,
      x
      );

   // OUTLET ESQUERDO
   sys_vgui(".x%lx.c create rectangle %d %d %d %d -tags {%xrr} -fill #FFFFFF\n",
      x->canvas,
      x0 + 0,
      y0 + x->size - 2,
      x0 + 8,
      y0 + x->size,
      x
      );

   // Light gray background
   sys_vgui(".x%lx.c create arc %d %d %d %d -tags {%xrr} -width 0 -outline #333 -fill #EFEFEF -extent -270 -start 225\n",
      x->canvas,
      x0,
      y0,
      x0 + x->size,
      y0 + x->size,
      x
      );

   // Blue arc with value #42c2f4
   int arc = -(x->value * 270) / (x->max - x->min);
   sys_vgui(".x%lx.c create arc %d %d %d %d -tags {%xrr %xarc} -width 0 -outline #42c2f4 -fill #42c2f4 -extent %d -start 225\n",
      x->canvas,
      x0+1,
      y0+1,
      x0 + x->size-1,
      y0 + x->size-1,
      x,
      x,
      arc
      );

   // White Marks
   for (int i = 0 ; i < 27 ; i++){
       sys_vgui(".x%lx.c create arc %d %d %d %d -tags {%xrr} -fill #FFF -outline #FFF -width 1 -extent -1 -start %d\n", x->canvas, x0 + 1, y0 + 1 , x0 + x->size - 1, y0 + x->size - 1, x, -45 + (i * 10));
    }

   // Gray button background
   sys_vgui(".x%lx.c create oval %d %d %d %d -tags {%xrr} -width 1 -fill #333 -outline #FFF -width 4\n",
      x->canvas,
      x0 + (t_int)(0.2 * x->size),
      y0 + (t_int)(0.2 * x->size),
      x0 + (t_int)(0.8 * x->size),
      y0 + (t_int)(0.8 * x->size),
      x
      );

   // Black Button
   sys_vgui(".x%lx.c create oval %d %d %d %d -tags {%xrr} -width 1 -fill #000 -outline #000\n",
      x->canvas,
      x0 + (t_int)(0.3 * x->size),
      y0 + (t_int)(0.3 * x->size),
      x0 + (t_int)(0.7 * x->size),
      y0 + (t_int)(0.7 * x->size),
      x
      );

   // Black needle
   sys_vgui(".x%lx.c create arc %d %d %d %d -tags {%xrr %xneed} -extent 2 -start %d -width 1 -outline #222 -fill #000 -width 2\n",
      x->canvas,
      x0 + (t_int)(0.15 * x->size),
      y0 + (t_int)(0.15 * x->size),
      x0 + (t_int)(0.85 * x->size),
      y0 + (t_int)(0.85 * x->size),
      x,
      x,
      arc - 135
      );

   // Top Black Button
   sys_vgui(".x%lx.c create oval %d %d %d %d -tags {%xrr} -width 1 -fill #000 -outline #000\n",
      x->canvas,
      x0 + (t_int)(0.45 * x->size),
      y0 + (t_int)(0.45 * x->size),
      x0 + (t_int)(0.55 * x->size),
      y0 + (t_int)(0.55 * x->size),
      x
      );
   canvas_fixlinesfor(x->glist, (t_text *)x);
}
// ---------------------------------------------------
// Erase
// ---------------------------------------------------
static void knob_erase(t_knob *x){
    t_canvas * canvas = x->canvas;
    sys_vgui(".x%lx.c delete %xrr\n",canvas, x);
}

// ---------------------------------------------------
// The external GUI rectangle definition
// ---------------------------------------------------
static void knob_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2){
   t_knob *x = (t_knob *)z;
   *xp1 = x->x_obj.te_xpix;
   *yp1 = x->x_obj.te_ypix;
   *xp2 = x->x_obj.te_xpix + x->size;
   *yp2 = x->x_obj.te_ypix + x->size;
}

// ---------------------------------------------------
// How to make it visible / invisible
// ---------------------------------------------------
static void knob_vis(t_gobj *z, t_glist *glist, int vis){
   t_knob *x = (t_knob *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   x->glist = glist;
   x->canvas = canvas;

   if(vis){ // VISIBLE
      char buf[256];
      sprintf(buf,"knob%lx", (long unsigned int)x);
      pd_bind(&x->x_obj.ob_pd, gensym(buf));

      knob_draw(x);
      sys_vgui(".x%lx.c bind %xrr <ButtonPress-1> {\n knob_mousepress%x %%x %%y %%b\n}\n", x->canvas, x, x);
      sys_vgui(".x%lx.c bind %xrr <B1-Motion> {\n knob_mousemotion%x %%x %%y\n}\n", x->canvas, x, x);

      sys_vgui("proc knob_mousepress%x {x y b} {\n", x);
      sys_vgui("    if {$b == 1} {\n");
      sys_vgui("        pd [concat knob%x mousepress $x $y\\;]\n", x);
      sys_vgui("    }\n");
      sys_vgui("}\n");

      sys_vgui("proc knob_mousemotion%x {x y} {\n", x);
      sys_vgui("    set cmd [concat knob%x mousemotion $x $y\\;]\n", x);
      sys_vgui("    pd $cmd\n");
      sys_vgui("}\n");

   }else{
      char buf[256];
      sprintf(buf,"knob%lx", (long unsigned int)x);
      pd_unbind(&x->x_obj.ob_pd, gensym(buf));
      knob_erase(x);
      return;
   }
}
// ---------------------------------------------------
// what to do when moved
// ---------------------------------------------------
static void knob_displace(t_gobj *z, t_glist *glist,int dx, int dy){
   t_canvas * canvas = glist_getcanvas(glist);
   t_knob *x = (t_knob *)z;
   x->x_obj.te_xpix += dx;
   x->x_obj.te_ypix += dy;

   // MOVE THE BLUE ONE
   sys_vgui(".x%lx.c move %xSEL %d %d\n", canvas, x, dx, dy);
   // MOVE the main rectangle
   sys_vgui(".x%lx.c move %xrr %d %d\n", x->canvas, x, dx, dy);

   canvas_fixlinesfor(glist, (t_text *)x);
}
// ---------------------------------------------------
// What to do when selected
// ---------------------------------------------------
static void knob_select(t_gobj *z, t_glist *glist, int state){
   t_knob *x = (t_knob *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   if (state) {
      sys_vgui(".x%lx.c create rectangle %d %d %d %d -tags %xSEL -outline blue\n",
      canvas,
      x->x_obj.te_xpix,
      x->x_obj.te_ypix,
      x->x_obj.te_xpix + x->size,
      x->x_obj.te_ypix + x->size,
      x
      );
  }else {
   sys_vgui(".x%lx.c delete %xSEL\n",canvas, x);
  }
}

// ---------------------------------------------------
// What to do when deleted
// ---------------------------------------------------
static void knob_delete(t_gobj *z, t_glist *glist){
   t_text *x = (t_text *)z;
   canvas_deletelinesfor(glist_getcanvas(glist), x);
}
// ---------------------------------------------------
// What to do when saved
// ---------------------------------------------------
static void knob_save(t_gobj *z, t_binbuf *b){
    t_knob *x = (t_knob *)z;
    binbuf_addv(b,
                "ssiisiiii",
                gensym("#X"),
                gensym("obj"),
                (t_int)x->x_obj.te_xpix,
                (t_int)x->x_obj.te_ypix,
                gensym("knob"),
                (t_int)x->size,
                (t_int)x->min,
                (t_int)x->max,
                (t_int)x->value);
    binbuf_addv(b, ";");

}
// ---------------------------------------------------
// The properties window
// ---------------------------------------------------
static void knob_properties(t_gobj *z, t_glist *list){
    t_knob *x = (t_knob *)z;
    char cmdbuf[256];
    sprintf(cmdbuf, "knob_properties %%s %d %f %f %f\n",
        (t_int)x->size,
        x->min,
        x->max,
        x->value);
    gfxstub_new(&x->x_obj.ob_pd, x, cmdbuf);
}

// ---------------------------------------------------
// Set Properties
// ---------------------------------------------------
static void knob_set_properties(t_knob *x, t_floatarg size,
                t_floatarg min, t_floatarg max, t_floatarg value){
    x->size = (t_int)size;
    x->min = min;
    x->max = max;
    x->value = value;
}


// ---------------------------------------------------
// Apply changes of property windows
// ---------------------------------------------------
static void knob_apply(t_knob *x,
            t_floatarg size, t_floatarg min,
            t_floatarg max, t_floatarg value){
    knob_erase(x);
    knob_set_properties(x, size, min, max, value);
    knob_draw(x);
}

//EOF GUI stuff ---------------------------------------

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void knob_setup(void) {
   knob_class = class_new(gensym("knob"),
      (t_newmethod) knob_new, // Constructor
      (t_method) knob_destroy, // Destructor
      sizeof (t_knob),
      CLASS_DEFAULT,
      A_DEFFLOAT,
      A_DEFFLOAT,
      A_DEFFLOAT,
      A_DEFFLOAT,
      0);//Must always ends with a zero

   class_addbang(knob_class, knob_bang_bang_method);
   class_addfloat(knob_class, knob_value_float_method);

   class_addmethod(knob_class, (t_method) knob_size, gensym("size"), A_DEFFLOAT, 0);
   class_addmethod(knob_class, (t_method) knob_min, gensym("min"), A_DEFFLOAT, 0);
   class_addmethod(knob_class, (t_method) knob_max, gensym("max"), A_DEFFLOAT, 0);

// Methods to receive TCL/TK events
   class_addmethod(knob_class, (t_method) knob_mousepress,gensym("mousepress"), A_FLOAT, A_FLOAT, 0);
   class_addmethod(knob_class, (t_method) knob_mousemotion,gensym("mousemotion"), A_FLOAT, A_FLOAT, 0);
   class_addmethod(knob_class, (t_method) knob_apply, gensym("apply"), A_FLOAT, A_FLOAT, A_FLOAT, A_FLOAT, 0);

//   GUI STUFF---------------------------
   knob_widgetbehavior.w_getrectfn = knob_getrect;
   knob_widgetbehavior.w_visfn= knob_vis;
   knob_widgetbehavior.w_displacefn= knob_displace;
   knob_widgetbehavior.w_selectfn= knob_select;
   knob_widgetbehavior.w_activatefn = NULL;
   knob_widgetbehavior.w_deletefn = knob_delete;
   knob_widgetbehavior.w_clickfn = NULL; // not using pd click function
   class_setpropertiesfn(knob_class, knob_properties);
   class_setsavefn(knob_class, knob_save);
   class_setwidget(knob_class, &knob_widgetbehavior);

sys_vgui("if {[catch {pd}] } {\n");
sys_vgui("    proc pd {args} {pdsend [join $args \" \"]}\n");
sys_vgui("}\n");

sys_vgui("proc knob_ok {id} {\n");
sys_vgui("    knob_apply $id\n");
sys_vgui("    knob_cancel $id\n");
sys_vgui("}\n");

sys_vgui("proc knob_cancel {id} {\n");
sys_vgui("    set cmd [concat $id cancel \\;]\n");
sys_vgui("    pd $cmd\n");
sys_vgui("}\n");

sys_vgui("proc knob_apply {id} {\n");
sys_vgui("    set vid [string trimleft $id .]\n");
sys_vgui("    set var_size [concat var_size_$vid]\n");
sys_vgui("    set var_min [concat var_min_$vid]\n");
sys_vgui("    set var_max [concat var_max_$vid]\n");
sys_vgui("    set var_value [concat var_value_$vid]\n");
sys_vgui("\n");
sys_vgui("    global $var_size\n");
sys_vgui("    global $var_max\n");
sys_vgui("    global $var_min\n");
sys_vgui("    global $var_value\n");
sys_vgui("\n");
sys_vgui("    set cmd [concat $id apply \\\n");
sys_vgui("        [eval concat $$var_size] \\\n");
sys_vgui("        [eval concat $$var_min] \\\n");
sys_vgui("        [eval concat $$var_max] \\\n");
sys_vgui("        [eval concat $$var_value] \\;]\n");
sys_vgui("    puts $cmd\n");
sys_vgui("    pd $cmd\n");
sys_vgui("}\n");

sys_vgui("proc knob_properties {id size min max value} {\n");
sys_vgui("    set vid [string trimleft $id .]\n");
sys_vgui("    set var_size [concat var_size_$vid]\n");
sys_vgui("    set var_min [concat var_min_$vid]\n");
sys_vgui("    set var_max [concat var_max_$vid]\n");
sys_vgui("    set var_value [concat var_value_$vid]\n");
sys_vgui("\n");
sys_vgui("    global $var_size\n");
sys_vgui("    global $var_min\n");
sys_vgui("    global $var_max\n");
sys_vgui("    global $var_value\n");
sys_vgui("\n");
sys_vgui("    set $var_size $size\n");
sys_vgui("    set $var_min $min\n");
sys_vgui("    set $var_max $max\n");
sys_vgui("    set $var_value $value\n");
sys_vgui("\n");
sys_vgui("    toplevel $id\n");
sys_vgui("    wm title $id {Knob}\n");
sys_vgui("    wm protocol $id WM_DELETE_WINDOW [concat knob_cancel $id]\n");
sys_vgui("\n");
sys_vgui("    label $id.label -text {Knob}\n");
sys_vgui("    pack $id.label -side top\n");
sys_vgui("\n");
sys_vgui("    frame $id.size\n");
sys_vgui("    pack $id.size -side top\n");
sys_vgui("    label $id.size.lsize -text \"Size:\"\n");
sys_vgui("    entry $id.size.size -textvariable $var_size -width 7\n");
sys_vgui("    pack $id.size.lsize $id.size.size -side left\n");
sys_vgui("\n");
sys_vgui("    frame $id.minmax\n");
sys_vgui("    pack $id.minmax -side top\n");
sys_vgui("    label $id.minmax.lmax -text \"Max:\"\n");
sys_vgui("    entry $id.minmax.max -textvariable $var_max -width 7\n");
sys_vgui("    label $id.minmax.lmin -text \"Min:\"\n");
sys_vgui("    entry $id.minmax.min -textvariable $var_min -width 7\n");
sys_vgui("    pack $id.minmax.lmin $id.minmax.min $id.minmax.lmax $id.minmax.max -side left\n");
sys_vgui("\n");
sys_vgui("    frame $id.value\n");
sys_vgui("    pack $id.value -side top\n");
sys_vgui("    label $id.value.lvalue -text \"Value:\"\n");
sys_vgui("    entry $id.value.value -textvariable $var_value -width 7\n");
sys_vgui("    pack $id.value.lvalue $id.value.value -side left\n");
sys_vgui("\n");
sys_vgui("    frame $id.buttonframe\n");
sys_vgui("    pack $id.buttonframe -side bottom -fill x -pady 2m\n");
sys_vgui("    button $id.buttonframe.cancel -text {Cancel} -command \"knob_cancel $id\"\n");
sys_vgui("    button $id.buttonframe.apply -text {Apply} -command \"knob_apply $id\"\n");
sys_vgui("    button $id.buttonframe.ok -text {OK} -command \"knob_ok $id\"\n");
sys_vgui("    pack $id.buttonframe.cancel -side left -expand 1\n");
sys_vgui("    pack $id.buttonframe.apply -side left -expand 1\n");
sys_vgui("    pack $id.buttonframe.ok -side left -expand 1\n");
sys_vgui("\n");
sys_vgui("    focus $id.size.size\n");
sys_vgui("}\n");

}
// EOF---------------------------------------------------
